"use client";

import Link from "next/link";
import { Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { AlertTriangle, X } from "lucide-react";
import { Eyebrow } from "@/components/ui/panel";
import { cn } from "@/lib/utils";

type LegalTab = "privacy" | "terms" | "ai";

const LEGAL_CONTENT: Record<LegalTab, { title: string; sections: { h: string; p: string }[] }> = {
  privacy: {
    title: "Privacy Policy",
    sections: [
      {
        h: "What we collect",
        p: "Your account details, each client's website and brand answers you give during setup, content you approve or write, and the OAuth tokens needed to post on a client's behalf on platforms you connect. We never see platform passwords — OAuth means they stay with the platform.",
      },
      {
        h: "How we use it",
        p: "To build brand profiles, draft and schedule posts you approve, and show mentions in your inbox for connected accounts. We don't sell your data or use it to train models.",
      },
      {
        h: "Third-party platforms",
        p: "When you connect X, LinkedIn or Facebook, those platforms' own privacy policies also apply to data they hold. Disconnecting an account revokes our stored token but doesn't delete anything already posted.",
      },
      {
        h: "Retention",
        p: "We keep workspace data while your account is active. Archiving a client keeps its data so it can be restored; deleting your workspace removes stored profiles, posts and tokens.",
      },
      {
        h: "Your rights",
        p: "You can access, export or delete your data at any time from Settings, or by contacting the workspace owner.",
      },
    ],
  },
  terms: {
    title: "Terms of Service",
    sections: [
      {
        h: "Using CampaignForge",
        p: "You must own or be authorized to manage every brand and social account you connect. You're responsible for what gets published under those accounts, even when a draft started as an AI suggestion.",
      },
      {
        h: "AI-generated content",
        p: "Drafts are written by AI and never publish without explicit human approval. You are responsible for checking accuracy, claims and tone before approving — the moderation check is advisory, not a guarantee of compliance with any platform's policies.",
      },
      {
        h: "Prohibited use",
        p: "No spam, harassment, impersonation, or content that violates a connected platform's terms. We can suspend workspaces that abuse the service or put platform API access at risk for other users.",
      },
      {
        h: "Termination",
        p: "You can stop using CampaignForge and disconnect all accounts at any time. We may suspend workspaces for terms violations, with notice where reasonably possible.",
      },
      {
        h: "Liability",
        p: "CampaignForge is provided as-is. We're not liable for the consequences of content you approved and published, or for platform outages, rate limits or policy changes outside our control.",
      },
    ],
  },
  ai: {
    title: "AI-Generated Content Notice",
    sections: [
      {
        h: "How drafts are made",
        p: "Posts, replies, emails, ads and calendar suggestions are generated by large language models from the client's brand profile and your settings. Nothing is published or sent without a human actively approving it first.",
      },
      {
        h: "Why this matters",
        p: "AI can misjudge tone, invent plausible-sounding but wrong specifics, or miss context only you know. Treat every draft as a starting point, not a finished, verified post.",
      },
      {
        h: "Your responsibility",
        p: "You're the one publishing under the client's name and accounts. Read every draft before approving, especially anything with numbers, claims, or comparisons to competitors.",
      },
    ],
  },
};

function isTab(value: string | null): value is LegalTab {
  return value === "privacy" || value === "terms" || value === "ai";
}

function LegalBody() {
  const params = useSearchParams();
  const raw = params.get("tab");
  const tab: LegalTab = isTab(raw) ? raw : "privacy";
  const content = LEGAL_CONTENT[tab];

  return (
    <div className="mx-auto max-w-3xl px-6 py-10">
      <div className="mb-5 flex items-center justify-between">
        <Eyebrow>Legal</Eyebrow>
        <Link href="/welcome" className="flex items-center gap-1.5 font-mono text-[11.5px] text-muted hover:text-ink">
          <X className="h-3 w-3" /> Back
        </Link>
      </div>

      <div className="mb-5 flex flex-wrap gap-1 font-mono text-xs">
        {(Object.keys(LEGAL_CONTENT) as LegalTab[]).map((id) => (
          <Link
            key={id}
            href={`/legal?tab=${id}`}
            aria-current={tab === id ? "page" : undefined}
            className={cn(
              "rounded-md border px-3 py-1.5 transition-colors",
              tab === id ? "border-accent bg-accent text-on-accent" : "border-line text-muted hover:text-ink"
            )}
          >
            {LEGAL_CONTENT[id].title}
          </Link>
        ))}
      </div>

      <div key={tab} className="animate-screen-in rounded-xl border border-line bg-panel/70 p-6 backdrop-blur-xl">
        <div className="mb-4 flex items-center gap-2 rounded-md border border-accent/30 bg-accent/10 px-3 py-2">
          <AlertTriangle className="h-3 w-3 shrink-0 text-accent-text" />
          <span className="font-mono text-[10.5px] text-accent-text">
            Draft wording — have this reviewed by a lawyer before relying on it.
          </span>
        </div>
        <h1 className="font-mono text-xl text-ink">{content.title}</h1>
        <div className="mt-4 space-y-4">
          {content.sections.map((s) => (
            <div key={s.h}>
              <h2 className="mb-1 font-mono text-xs text-accent-text">{s.h}</h2>
              <p className="text-[13px] leading-relaxed text-slate-600">{s.p}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/** Public (see middleware.ts) so the footer links work signed out too. */
export default function LegalPage() {
  return (
    <div className="app-shell app-canvas min-h-screen">
      <Suspense fallback={null}>
        <LegalBody />
      </Suspense>
    </div>
  );
}
